* About
  Scripts to help me administer Solaris 10.

  This scripts are a bit bias'd towards how I do things, and you may
  need to modify them accordingly.

  For instance, I use virtual NICs with crossbow for networking my
  zones.

  Also, I map my home directory into each zone.  

  Search for and alter the variables in the config section near the
  front, and the contents of the zone_tmplt_str variable to change these
  things.  

  Also, please make suggestions.
* Requirements
  Python2.4 that comes with Solaris 10.  It should work with newer,
  including what comes with Solaris 11.  I don't want you to have to use
  anything further than what is installed to use this. 

  You may need a suffuciently new version of Solaris 10 though, or else
  to modify the scripts.  I believe you need build 105 or newer.
* Todo
** Generate and install a site.xml file.
   installs to zone_storage_path/ZONE_NAME/root/var/svc/profile
   
   Probably should copy from a freshly installed zone, immediately after
   my zone_service_cleanup script was run.  Then, with the site.xml, the
   cleanup script wouldn't be needed.
